# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install -g node-gyp
  displayName: 'install node-gyp'
 
- script: npm install --global --production windows-build-tools@4.0.0
  displayName: 'install windows-build-tools'

- task: CmdLine@2
  inputs:
    script: 'SET VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120'

- script: npm install
  displayName: 'npm install'
